### ISSUE TITLE
Kategorien

### ISSUE THREAD

**Issue by IngaMList** [SeGePae/segepae#20]
Danke für die Ergänzung! 
Es fehlt die dritte Ebene bei denen, die eine dritte Ebene haben (2.2, 6.1 und 6.2)
Bei 3.1 und 3.2 fehlt der Unterstrich.

**Comment by IngaMList** [comment]
Nein, ganz sicher sind die noch weiter ausdifferenziert.

**Comment by IngaMList** [comment]
In der Bibliographie selbst unter dem Klickfeld Kategorien tauchen die auch auf.

**Comment by LinguList** [comment]
wird geschlossen, wenn Inga die Wörter ein bissel kleiner gemacht hat.

**Comment by IngaMList** [comment]
Kategoriennamen sind jetzt gekürzt.

**Comment by LinguList** [comment]
sind wir dann fergit?

**Comment by IngaMList** [comment]
Ja, ich werde heute Mittag mit meiner Kollegin klären, wie wir bei der Webpage den Namen ändern. Sonst ist alles fertig.
