### ISSUE TITLE
veröffentlichung und erste Version auf Zenodo

### ISSUE THREAD

**Issue by LinguList** [SeGePae/segepae#23]
Das muss sein, denn dadurch kann dann erstens auch der Code referenziert werden und zweitens kann man auf die Bibtex-Datei verweisen, die Nutzer runterladen können. Dafür würde ich das Repo öffentlich machen und auf die Organisation übertragen.

**Comment by IngaMList** [comment]
Ich verstehe den Punkt nicht. Die erste Version ist bereits bei Zenodo veröffentlicht. Was meinst du?

**Comment by IngaMList** [comment]
Hast du ja bereits gemacht! Jetzt sehe ich, was du meinst. Super! Dann kann man das hier schließen, oder?

**Comment by LinguList** [comment]
So, jetzt bitte noch mal einen Release draften, warten, bis der auf Zenodo erscheint und dann das hier abschließen.

**Comment by IngaMList** [comment]
Kann ich nicht, ich kann auf die Datei bei Zenodo nicht zugreifen, habe vermutlich keine Rechte?? D.h., es bringt nichts, dass die DOI schon feststeht, ich kann keine weitere Version hinzufügen

**Comment by IngaMList** [comment]
Ich habe es geschafft - also einen neuen Release gedraftet und veröffentlicht.
