### ISSUE TITLE
Veröffentlicht!

### ISSUE THREAD

**Issue by IngaMList** [SeGePae/segepae#25]
Auf der Webpage ist alles jetzt veröffentlicht. Ich werde mich gleich um die Zenodo-Veröffentlichung kümmern. Vorher ist aber noch wichtig: Ich habe letzte Veränderungen auf der Einführungs- und Autorinnen-Seite vorgenommen. Kannst du deswegen bitte noch einmal das "rüberziehen"? DANACH erst soll ich die Veröffentlichung bei Zenodo vornehmen, richtig?

**Comment by LinguList** [comment]
schau noch mal online, und wenn's läuft, mach's zu. Schik mir dann auch mal den link zu eurer Instituts-Website mit der Bibliographie...

**Comment by IngaMList** [comment]
https://www.forschungsnetzwerk-gegen-sexualisierte-gewalt.de/de/internationales-monitoring

**Comment by IngaMList** [comment]
Hab gerade noch was verändert, du warst zu schnell...

**Comment by IngaMList** [comment]
Kannst du es bitte noch ein letztes Mal machen? Dann sind wir wirklich fertig und ich veröffentliche auf Zenodo!

**Comment by IngaMList** [comment]
Also, nun ist es fertig - jetzt fehlt nur noch das Update für die Webseite (Sec 1 und Sec 5 wurden angepasst). Dann sind wir wirklich durch!!!

**Comment by LinguList** [comment]
Okay, als Hausaufgabe installierst du python3 ;-) dann kannst du den code auch selber laufen lassen...

**Comment by LinguList** [comment]
wobei das kein Problem ist: ich update, die neue Version ist dann eben später noch mal etc., du kannst auch einfach v1.1 oder so aufsetzen danach...

**Comment by LinguList** [comment]
[hier](https://zenodo.org/record/1048866) musst du jetzt eben noch die Metadaten ändern, damit da dann auch steht "source code und application code", etc. Ist aber über zenodo kein Problem.

**Comment by IngaMList** [comment]
Ich weiß nicht, was du meinst. Meinst du den Einleitungstext? Das kann ich gleich machen.
