### ISSUE TITLE
Sec4

### ISSUE THREAD

**Issue by IngaMList** [SeGePae/segepae#27]
Gibt es die Möglichkeit, eine PDF einzubetten? Oder soll ich die erst über Zenodo hochladen und hier dann nur den Link zu Zenodo einfügen? (Es geht um den Vortrag.)

**Comment by LinguList** [comment]
Ich würde lieber Links einfügen.

**Comment by IngaMList** [comment]
Gut! Habe beides über Zenodo veröffentlicht und verlinkt.
